name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  pages:
    name: Build gh-pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
  tr:
    name: Build TR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
          W3C_BUILD_OVERRIDE: |
            specStatus: CRD